import "./globals.css"
import { Inter } from "next/font/google"
import StyledComponentsRegistry from "@/lib/rergisty"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Marvel Searcher",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <StyledComponentsRegistry>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </StyledComponentsRegistry>
  )
}
