import "./globals.css"

import StyledComponentsRegistry from "@/lib/rergisty"
import CustomProvider from "@/components/Context/Context"
import Header from "@/components/Header/Header"

export const metadata = {
  title: "Marvel Searcher",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <StyledComponentsRegistry>
      <CustomProvider>
        <html lang="en">
          <body>
            <Header />
            {children}
          </body>
        </html>
      </CustomProvider>
    </StyledComponentsRegistry>
  )
}
